/*
 * ConfigCat Public Management API
 * The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 
 *
 * The version of the OpenAPI document: v1
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.configcat.publicapi.java.client.model;

import java.util.Objects;
import com.configcat.publicapi.java.client.model.AuditLogSettingValueV2EvaluationFormulaConditionModel;
import com.configcat.publicapi.java.client.model.AuditLogSettingValueV2EvaluationFormulaPercentageOptionModel;
import com.configcat.publicapi.java.client.model.ValueModel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.configcat.publicapi.java.client.JSON;

/**
 * A targeting rule that specifies conditions and value(s) to return when those conditions are met.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-05T13:17:19.774498623Z[Etc/UTC]", comments = "Generator version: 7.23.0")
public class AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel {
  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nullable
  private ValueModel value;

  public static final String SERIALIZED_NAME_VALUE_PREDEFINED_VARIATION_NAME = "valuePredefinedVariationName";
  @SerializedName(SERIALIZED_NAME_VALUE_PREDEFINED_VARIATION_NAME)
  @javax.annotation.Nullable
  private String valuePredefinedVariationName;

  public static final String SERIALIZED_NAME_CONDITIONS = "conditions";
  @SerializedName(SERIALIZED_NAME_CONDITIONS)
  @javax.annotation.Nonnull
  private List<AuditLogSettingValueV2EvaluationFormulaConditionModel> conditions = new ArrayList<>();

  public static final String SERIALIZED_NAME_PERCENTAGE_OPTIONS = "percentageOptions";
  @SerializedName(SERIALIZED_NAME_PERCENTAGE_OPTIONS)
  @javax.annotation.Nonnull
  private List<AuditLogSettingValueV2EvaluationFormulaPercentageOptionModel> percentageOptions = new ArrayList<>();

  public AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel() {
  }

  public AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel value(@javax.annotation.Nullable ValueModel value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nullable
  public ValueModel getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nullable ValueModel value) {
    this.value = value;
  }


  public AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel valuePredefinedVariationName(@javax.annotation.Nullable String valuePredefinedVariationName) {
    this.valuePredefinedVariationName = valuePredefinedVariationName;
    return this;
  }

  /**
   * Optional name of the predefined variation for the value.
   * @return valuePredefinedVariationName
   */
  @javax.annotation.Nullable
  public String getValuePredefinedVariationName() {
    return valuePredefinedVariationName;
  }

  public void setValuePredefinedVariationName(@javax.annotation.Nullable String valuePredefinedVariationName) {
    this.valuePredefinedVariationName = valuePredefinedVariationName;
  }


  public AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel conditions(@javax.annotation.Nonnull List<AuditLogSettingValueV2EvaluationFormulaConditionModel> conditions) {
    this.conditions = conditions;
    return this;
  }

  public AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel addConditionsItem(AuditLogSettingValueV2EvaluationFormulaConditionModel conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

  /**
   * List of conditions that must be satisfied for this targeting rule to apply.
   * @return conditions
   */
  @javax.annotation.Nonnull
  public List<AuditLogSettingValueV2EvaluationFormulaConditionModel> getConditions() {
    return conditions;
  }

  public void setConditions(@javax.annotation.Nonnull List<AuditLogSettingValueV2EvaluationFormulaConditionModel> conditions) {
    this.conditions = conditions;
  }


  public AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel percentageOptions(@javax.annotation.Nonnull List<AuditLogSettingValueV2EvaluationFormulaPercentageOptionModel> percentageOptions) {
    this.percentageOptions = percentageOptions;
    return this;
  }

  public AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel addPercentageOptionsItem(AuditLogSettingValueV2EvaluationFormulaPercentageOptionModel percentageOptionsItem) {
    if (this.percentageOptions == null) {
      this.percentageOptions = new ArrayList<>();
    }
    this.percentageOptions.add(percentageOptionsItem);
    return this;
  }

  /**
   * List of percentage options when percentage-based user bucketing (for A/B testing) is used in the targeting rule.
   * @return percentageOptions
   */
  @javax.annotation.Nonnull
  public List<AuditLogSettingValueV2EvaluationFormulaPercentageOptionModel> getPercentageOptions() {
    return percentageOptions;
  }

  public void setPercentageOptions(@javax.annotation.Nonnull List<AuditLogSettingValueV2EvaluationFormulaPercentageOptionModel> percentageOptions) {
    this.percentageOptions = percentageOptions;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel instance itself
   */
  public AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel auditLogSettingValueV2EvaluationFormulaTargetingRuleModel = (AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel) o;
    return Objects.equals(this.value, auditLogSettingValueV2EvaluationFormulaTargetingRuleModel.value) &&
        Objects.equals(this.valuePredefinedVariationName, auditLogSettingValueV2EvaluationFormulaTargetingRuleModel.valuePredefinedVariationName) &&
        Objects.equals(this.conditions, auditLogSettingValueV2EvaluationFormulaTargetingRuleModel.conditions) &&
        Objects.equals(this.percentageOptions, auditLogSettingValueV2EvaluationFormulaTargetingRuleModel.percentageOptions)&&
        Objects.equals(this.additionalProperties, auditLogSettingValueV2EvaluationFormulaTargetingRuleModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, valuePredefinedVariationName, conditions, percentageOptions, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    valuePredefinedVariationName: ").append(toIndentedString(valuePredefinedVariationName)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    percentageOptions: ").append(toIndentedString(percentageOptions)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("value", "valuePredefinedVariationName", "conditions", "percentageOptions"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("value", "valuePredefinedVariationName", "conditions", "percentageOptions"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel is not found in the empty JSON string", AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) {
      // validate the required field `value`
      ValueModel.validateJsonElement(jsonObj.get("value"));
      }
      if ((jsonObj.get("valuePredefinedVariationName") != null && !jsonObj.get("valuePredefinedVariationName").isJsonNull()) && !jsonObj.get("valuePredefinedVariationName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `valuePredefinedVariationName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("valuePredefinedVariationName").toString()));
      }
      if (jsonObj.get("conditions") != null) {
        if (!jsonObj.get("conditions").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `conditions` to be an array in the JSON string but got `%s`", jsonObj.get("conditions").toString()));
        }
        JsonArray jsonArrayconditions = jsonObj.getAsJsonArray("conditions");
        // validate the required field `conditions` (array)
        for (int i = 0; i < jsonArrayconditions.size(); i++) {
          AuditLogSettingValueV2EvaluationFormulaConditionModel.validateJsonElement(jsonArrayconditions.get(i));
        }
      }
      if (jsonObj.get("percentageOptions") != null) {
        if (!jsonObj.get("percentageOptions").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `percentageOptions` to be an array in the JSON string but got `%s`", jsonObj.get("percentageOptions").toString()));
        }
        JsonArray jsonArraypercentageOptions = jsonObj.getAsJsonArray("percentageOptions");
        // validate the required field `percentageOptions` (array)
        for (int i = 0; i < jsonArraypercentageOptions.size(); i++) {
          AuditLogSettingValueV2EvaluationFormulaPercentageOptionModel.validateJsonElement(jsonArraypercentageOptions.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel.class));

       return (TypeAdapter<T>) new TypeAdapter<AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel>() {
           @Override
           public void write(JsonWriter out, AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel
   * @throws IOException if the JSON string is invalid with respect to AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel
   */
  public static AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel.class);
  }

  /**
   * Convert an instance of AuditLogSettingValueV2EvaluationFormulaTargetingRuleModel to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

