/*
 * ConfigCat Public Management API
 * The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 
 *
 * The version of the OpenAPI document: v1
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.configcat.publicapi.java.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.configcat.publicapi.java.client.JSON;

/**
 * Model representing an approval on a Change Request.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-05T13:17:19.774498623Z[Etc/UTC]", comments = "Generator version: 7.23.0")
public class ChangeRequestApprovalModel {
  public static final String SERIALIZED_NAME_CHANGE_REQUEST_APPROVAL_ID = "changeRequestApprovalId";
  @SerializedName(SERIALIZED_NAME_CHANGE_REQUEST_APPROVAL_ID)
  @javax.annotation.Nonnull
  private Long changeRequestApprovalId;

  public static final String SERIALIZED_NAME_USER_EMAIL = "userEmail";
  @SerializedName(SERIALIZED_NAME_USER_EMAIL)
  @javax.annotation.Nonnull
  private String userEmail;

  public static final String SERIALIZED_NAME_USER_FULL_NAME = "userFullName";
  @SerializedName(SERIALIZED_NAME_USER_FULL_NAME)
  @javax.annotation.Nonnull
  private String userFullName;

  public static final String SERIALIZED_NAME_APPROVED_AT = "approvedAt";
  @SerializedName(SERIALIZED_NAME_APPROVED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime approvedAt;

  public static final String SERIALIZED_NAME_DISMISSED_AT = "dismissedAt";
  @SerializedName(SERIALIZED_NAME_DISMISSED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime dismissedAt;

  public ChangeRequestApprovalModel() {
  }

  public ChangeRequestApprovalModel changeRequestApprovalId(@javax.annotation.Nonnull Long changeRequestApprovalId) {
    this.changeRequestApprovalId = changeRequestApprovalId;
    return this;
  }

  /**
   * Identifier of the Change Request approval.
   * @return changeRequestApprovalId
   */
  @javax.annotation.Nonnull
  public Long getChangeRequestApprovalId() {
    return changeRequestApprovalId;
  }

  public void setChangeRequestApprovalId(@javax.annotation.Nonnull Long changeRequestApprovalId) {
    this.changeRequestApprovalId = changeRequestApprovalId;
  }


  public ChangeRequestApprovalModel userEmail(@javax.annotation.Nonnull String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

  /**
   * Email of the user who approved the Change Request.
   * @return userEmail
   */
  @javax.annotation.Nonnull
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(@javax.annotation.Nonnull String userEmail) {
    this.userEmail = userEmail;
  }


  public ChangeRequestApprovalModel userFullName(@javax.annotation.Nonnull String userFullName) {
    this.userFullName = userFullName;
    return this;
  }

  /**
   * Full name of the user who approved the Change Request.
   * @return userFullName
   */
  @javax.annotation.Nonnull
  public String getUserFullName() {
    return userFullName;
  }

  public void setUserFullName(@javax.annotation.Nonnull String userFullName) {
    this.userFullName = userFullName;
  }


  public ChangeRequestApprovalModel approvedAt(@javax.annotation.Nonnull OffsetDateTime approvedAt) {
    this.approvedAt = approvedAt;
    return this;
  }

  /**
   * The UTC date and time when the Change Request was approved.
   * @return approvedAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getApprovedAt() {
    return approvedAt;
  }

  public void setApprovedAt(@javax.annotation.Nonnull OffsetDateTime approvedAt) {
    this.approvedAt = approvedAt;
  }


  public ChangeRequestApprovalModel dismissedAt(@javax.annotation.Nullable OffsetDateTime dismissedAt) {
    this.dismissedAt = dismissedAt;
    return this;
  }

  /**
   * Optional UTC date and time when the approval was dismissed.
   * @return dismissedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getDismissedAt() {
    return dismissedAt;
  }

  public void setDismissedAt(@javax.annotation.Nullable OffsetDateTime dismissedAt) {
    this.dismissedAt = dismissedAt;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ChangeRequestApprovalModel instance itself
   */
  public ChangeRequestApprovalModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangeRequestApprovalModel changeRequestApprovalModel = (ChangeRequestApprovalModel) o;
    return Objects.equals(this.changeRequestApprovalId, changeRequestApprovalModel.changeRequestApprovalId) &&
        Objects.equals(this.userEmail, changeRequestApprovalModel.userEmail) &&
        Objects.equals(this.userFullName, changeRequestApprovalModel.userFullName) &&
        Objects.equals(this.approvedAt, changeRequestApprovalModel.approvedAt) &&
        Objects.equals(this.dismissedAt, changeRequestApprovalModel.dismissedAt)&&
        Objects.equals(this.additionalProperties, changeRequestApprovalModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeRequestApprovalId, userEmail, userFullName, approvedAt, dismissedAt, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangeRequestApprovalModel {\n");
    sb.append("    changeRequestApprovalId: ").append(toIndentedString(changeRequestApprovalId)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userFullName: ").append(toIndentedString(userFullName)).append("\n");
    sb.append("    approvedAt: ").append(toIndentedString(approvedAt)).append("\n");
    sb.append("    dismissedAt: ").append(toIndentedString(dismissedAt)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("changeRequestApprovalId", "userEmail", "userFullName", "approvedAt", "dismissedAt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("changeRequestApprovalId", "userEmail", "userFullName", "approvedAt", "dismissedAt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ChangeRequestApprovalModel
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChangeRequestApprovalModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ChangeRequestApprovalModel is not found in the empty JSON string", ChangeRequestApprovalModel.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ChangeRequestApprovalModel.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("userEmail").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `userEmail` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userEmail").toString()));
      }
      if (!jsonObj.get("userFullName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `userFullName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userFullName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChangeRequestApprovalModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChangeRequestApprovalModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChangeRequestApprovalModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChangeRequestApprovalModel.class));

       return (TypeAdapter<T>) new TypeAdapter<ChangeRequestApprovalModel>() {
           @Override
           public void write(JsonWriter out, ChangeRequestApprovalModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ChangeRequestApprovalModel read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ChangeRequestApprovalModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ChangeRequestApprovalModel given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ChangeRequestApprovalModel
   * @throws IOException if the JSON string is invalid with respect to ChangeRequestApprovalModel
   */
  public static ChangeRequestApprovalModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChangeRequestApprovalModel.class);
  }

  /**
   * Convert an instance of ChangeRequestApprovalModel to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

