/*
 * ConfigCat Public Management API
 * The purpose of this API is to access the ConfigCat platform programmatically. You can **Create**, **Read**, **Update** and **Delete** any entities like **Feature Flags, Configs, Environments** or **Products** within ConfigCat.  **Base API URL**: https://api.configcat.com  If you prefer the swagger documentation, you can find it here: [Swagger UI](https://api.configcat.com/swagger).  The API is based on HTTP REST, uses resource-oriented URLs, status codes and supports JSON  format.   **Important:** Do not use this API for accessing and evaluating feature flag values. Use the [SDKs](https://configcat.com/docs/sdk-reference/overview) or the [ConfigCat Proxy](https://configcat.com/docs/advanced/proxy/proxy-overview/) instead.  # OpenAPI Specification  The complete specification is publicly available in the following formats:  - [OpenAPI v3](https://api.configcat.com/docs/v1/swagger.json) - [Swagger v2](https://api.configcat.com/docs/v1/swagger.v2.json)  You can use it to generate client libraries in various languages with [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) or [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to interact with this API.  # Authentication This API uses the [Basic HTTP Authentication Scheme](https://en.wikipedia.org/wiki/Basic_access_authentication).   <!-- ReDoc-Inject: <security-definitions> -->  # Throttling and rate limits All the rate limited API calls are returning information about the current rate limit period in the following HTTP headers:  | Header | Description | | :- | :- | | X-Rate-Limit-Remaining | The maximum number of requests remaining in the current rate limit period. | | X-Rate-Limit-Reset     | The time when the current rate limit period resets.        |  When the rate limit is exceeded by a request, the API returns with a `HTTP 429 - Too many requests` status along with a `Retry-After` HTTP header. 
 *
 * The version of the OpenAPI document: v1
 * Contact: support@configcat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.configcat.publicapi.java.client.model;

import java.util.Objects;
import com.configcat.publicapi.java.client.model.ReferenceLineModel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.configcat.publicapi.java.client.JSON;

/**
 * ReferenceLinesModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-10T21:25:35.532049258Z[Etc/UTC]", comments = "Generator version: 7.7.0")
public class ReferenceLinesModel {
  public static final String SERIALIZED_NAME_FILE = "file";
  @SerializedName(SERIALIZED_NAME_FILE)
  private String _file;

  public static final String SERIALIZED_NAME_FILE_URL = "fileUrl";
  @SerializedName(SERIALIZED_NAME_FILE_URL)
  private String fileUrl;

  public static final String SERIALIZED_NAME_PRE_LINES = "preLines";
  @SerializedName(SERIALIZED_NAME_PRE_LINES)
  private List<ReferenceLineModel> preLines = new ArrayList<>();

  public static final String SERIALIZED_NAME_POST_LINES = "postLines";
  @SerializedName(SERIALIZED_NAME_POST_LINES)
  private List<ReferenceLineModel> postLines = new ArrayList<>();

  public static final String SERIALIZED_NAME_REFERENCE_LINE = "referenceLine";
  @SerializedName(SERIALIZED_NAME_REFERENCE_LINE)
  private ReferenceLineModel referenceLine;

  public ReferenceLinesModel() {
  }

  public ReferenceLinesModel _file(String _file) {
    this._file = _file;
    return this;
  }

  /**
   * The file&#39;s name in where the code reference has been found. (Appears on the ConfigCat Dashboard)
   * @return _file
   */
  @javax.annotation.Nonnull
  public String getFile() {
    return _file;
  }

  public void setFile(String _file) {
    this._file = _file;
  }


  public ReferenceLinesModel fileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
    return this;
  }

  /**
   * The file&#39;s url. (Used to point to the file on the repository&#39;s website)
   * @return fileUrl
   */
  @javax.annotation.Nullable
  public String getFileUrl() {
    return fileUrl;
  }

  public void setFileUrl(String fileUrl) {
    this.fileUrl = fileUrl;
  }


  public ReferenceLinesModel preLines(List<ReferenceLineModel> preLines) {
    this.preLines = preLines;
    return this;
  }

  public ReferenceLinesModel addPreLinesItem(ReferenceLineModel preLinesItem) {
    if (this.preLines == null) {
      this.preLines = new ArrayList<>();
    }
    this.preLines.add(preLinesItem);
    return this;
  }

  /**
   * The lines before the actual reference line.
   * @return preLines
   */
  @javax.annotation.Nonnull
  public List<ReferenceLineModel> getPreLines() {
    return preLines;
  }

  public void setPreLines(List<ReferenceLineModel> preLines) {
    this.preLines = preLines;
  }


  public ReferenceLinesModel postLines(List<ReferenceLineModel> postLines) {
    this.postLines = postLines;
    return this;
  }

  public ReferenceLinesModel addPostLinesItem(ReferenceLineModel postLinesItem) {
    if (this.postLines == null) {
      this.postLines = new ArrayList<>();
    }
    this.postLines.add(postLinesItem);
    return this;
  }

  /**
   * The lines after the actual reference line.
   * @return postLines
   */
  @javax.annotation.Nonnull
  public List<ReferenceLineModel> getPostLines() {
    return postLines;
  }

  public void setPostLines(List<ReferenceLineModel> postLines) {
    this.postLines = postLines;
  }


  public ReferenceLinesModel referenceLine(ReferenceLineModel referenceLine) {
    this.referenceLine = referenceLine;
    return this;
  }

  /**
   * Get referenceLine
   * @return referenceLine
   */
  @javax.annotation.Nonnull
  public ReferenceLineModel getReferenceLine() {
    return referenceLine;
  }

  public void setReferenceLine(ReferenceLineModel referenceLine) {
    this.referenceLine = referenceLine;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ReferenceLinesModel instance itself
   */
  public ReferenceLinesModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceLinesModel referenceLinesModel = (ReferenceLinesModel) o;
    return Objects.equals(this._file, referenceLinesModel._file) &&
        Objects.equals(this.fileUrl, referenceLinesModel.fileUrl) &&
        Objects.equals(this.preLines, referenceLinesModel.preLines) &&
        Objects.equals(this.postLines, referenceLinesModel.postLines) &&
        Objects.equals(this.referenceLine, referenceLinesModel.referenceLine)&&
        Objects.equals(this.additionalProperties, referenceLinesModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_file, fileUrl, preLines, postLines, referenceLine, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceLinesModel {\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    fileUrl: ").append(toIndentedString(fileUrl)).append("\n");
    sb.append("    preLines: ").append(toIndentedString(preLines)).append("\n");
    sb.append("    postLines: ").append(toIndentedString(postLines)).append("\n");
    sb.append("    referenceLine: ").append(toIndentedString(referenceLine)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("file");
    openapiFields.add("fileUrl");
    openapiFields.add("preLines");
    openapiFields.add("postLines");
    openapiFields.add("referenceLine");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("file");
    openapiRequiredFields.add("fileUrl");
    openapiRequiredFields.add("preLines");
    openapiRequiredFields.add("postLines");
    openapiRequiredFields.add("referenceLine");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ReferenceLinesModel
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ReferenceLinesModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReferenceLinesModel is not found in the empty JSON string", ReferenceLinesModel.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReferenceLinesModel.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("file").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `file` to be a primitive type in the JSON string but got `%s`", jsonObj.get("file").toString()));
      }
      if ((jsonObj.get("fileUrl") != null && !jsonObj.get("fileUrl").isJsonNull()) && !jsonObj.get("fileUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `fileUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fileUrl").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("preLines").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `preLines` to be an array in the JSON string but got `%s`", jsonObj.get("preLines").toString()));
      }

      JsonArray jsonArraypreLines = jsonObj.getAsJsonArray("preLines");
      // validate the required field `preLines` (array)
      for (int i = 0; i < jsonArraypreLines.size(); i++) {
        ReferenceLineModel.validateJsonElement(jsonArraypreLines.get(i));
      };
      // ensure the json data is an array
      if (!jsonObj.get("postLines").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `postLines` to be an array in the JSON string but got `%s`", jsonObj.get("postLines").toString()));
      }

      JsonArray jsonArraypostLines = jsonObj.getAsJsonArray("postLines");
      // validate the required field `postLines` (array)
      for (int i = 0; i < jsonArraypostLines.size(); i++) {
        ReferenceLineModel.validateJsonElement(jsonArraypostLines.get(i));
      };
      // validate the required field `referenceLine`
      ReferenceLineModel.validateJsonElement(jsonObj.get("referenceLine"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReferenceLinesModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReferenceLinesModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReferenceLinesModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReferenceLinesModel.class));

       return (TypeAdapter<T>) new TypeAdapter<ReferenceLinesModel>() {
           @Override
           public void write(JsonWriter out, ReferenceLinesModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ReferenceLinesModel read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ReferenceLinesModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ReferenceLinesModel given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ReferenceLinesModel
   * @throws IOException if the JSON string is invalid with respect to ReferenceLinesModel
   */
  public static ReferenceLinesModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReferenceLinesModel.class);
  }

  /**
   * Convert an instance of ReferenceLinesModel to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

